# Generated by Django 4.1.7 on 2023-03-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Имя не присвоено', max_length=128)),
                ('category_picture', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name': 'Категоря',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, null=True, unique=True, verbose_name='Наименование')),
                ('color', models.CharField(max_length=15, verbose_name='Цвет')),
                ('release_year', models.DateField(auto_now=True, verbose_name='Дата выпуска')),
                ('engine_capacity', models.CharField(max_length=4, verbose_name='Объем двигателя')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
            ],
        ),
    ]
